//! Configuration and policy file generation for `latchgate init`.
//!
//! Generates a minimal `latchgate.toml` with secure defaults. All omitted
//! fields fall back to `Config::default()` + runtime auto-resolution in
//! `latchgate up`. The generated config intentionally contains only the
//! fields that have no safe automatic default.

use std::path::Path;

use crate::embedded_policies;

use super::secure_file;
use latchgate_embed::embedded_presets::{Preset, WildcardGrant};
use latchgate_tui::IdentityChoice;

/// Resolved directories passed to config generation.
pub(crate) struct ConfigDirs<'a> {
    pub manifests: &'a std::path::Path,
    pub providers: &'a std::path::Path,
    pub data: &'a std::path::Path,
}

pub(crate) struct SigningKeyPaths<'a> {
    pub receipt: &'a Path,
    pub grant: &'a Path,
}

/// Build a minimal, commented `latchgate.toml`.
///
/// The generated config contains only the fields that require explicit
/// values — everything else is handled by `Config::default()` and runtime
/// path resolution. This keeps the user-facing config surface small and
/// avoids exposing security knobs that have only one safe value.
pub(crate) fn build_config_toml(
    operator_name: &str,
    api_key: &str,
    dpop_jkt: &str,
    dirs: &ConfigDirs<'_>,
    signing_keys: Option<&SigningKeyPaths<'_>>,
    identity: IdentityChoice,
) -> String {
    use toml_edit::{value, DocumentMut, Item, Table};

    let mut doc = DocumentMut::new();

    doc.decor_mut().set_prefix(
        "# LatchGate configuration.\n\
         #\n\
         # Generated by: latchgate init\n\
         # Docs: https://latchgate.dev/docs/config\n\
         #\n\
         # This file contains the minimal required settings. All omitted fields\n\
         # use secure defaults (UDS transport, strict sandbox, embedded policy\n\
         # engine, SQLite state). Customize as needed — run `latchgate doctor`\n\
         # to validate changes.\n\n",
    );

    // --- Filesystem root ---
    set_commented(
        &mut doc,
        "fs_root_path",
        value("."),
        "# Root directory for filesystem actions (relative paths resolved here).\n",
    );

    // --- Registry paths ---
    let manifests_str = dirs.manifests.display().to_string();
    let providers_str = dirs.providers.display().to_string();
    set_commented(
        &mut doc,
        "manifests_dir",
        value(&manifests_str),
        "\n# --- Registry ---\n\
         # Action manifests and WASM provider modules.\n",
    );
    doc["wasm_providers_dir"] = value(&providers_str);

    // --- Audit ---
    let ledger_str = dirs.data.join("audit.db").display().to_string();
    set_commented(
        &mut doc,
        "ledger_db_path",
        value(&ledger_str),
        "\n# --- Audit ---\n",
    );

    // --- Signing keys (only when persistent keys were chosen) ---
    if let Some(keys) = signing_keys {
        let receipt_key_str = keys.receipt.display().to_string();
        let grant_key_str = keys.grant.display().to_string();
        set_commented(
            &mut doc,
            "receipt_signing_key_path",
            value(&receipt_key_str),
            "\n# --- Signing keys (persistent across restarts) ---\n",
        );
        doc["grant_signing_key_path"] = value(&grant_key_str);
    }

    // --- Operator credentials ---
    let mut op_table = Table::new();
    op_table.insert("api_key", value(api_key));
    op_table.insert("dpop_jkt", value(dpop_jkt));

    let mut creds = Table::new();
    creds.decor_mut().set_prefix(
        "\n# --- Operator credentials ---\n\
         # Generated by `latchgate init`. The api_key is shown once at setup.\n",
    );
    creds.insert(operator_name, Item::Table(op_table));
    doc["operator_credentials"] = Item::Table(creds);

    // --- Commented guidance for common customizations ---
    let mut out = doc.to_string();

    // --- Identity ---
    match identity {
        IdentityChoice::Peercred => {
            let uid = rustix::process::getuid().as_raw();
            let principal = std::env::var("USER").unwrap_or_else(|_| "dev-user".into());
            out.push_str(&format!(
                "\n# --- Identity ---\n\
                 # Maps the current UID ({uid}) to a development principal.\n\
                 # Add more principals for multi-user setups.\n\
                 [identity]\n\
                 provider = \"peercred\"\n\
                 \n\
                 [identity.peercred]\n\
                 allow_unmapped = false\n\
                 \n\
                 [identity.peercred.principals.{uid}]\n\
                 principal = \"{principal}\"\n\
                 scopes = [\"tools:call\", \"operator:admin\"]\n",
            ));
        }
        IdentityChoice::None => {
            out.push_str(
                "\n# --- Identity ---\n\
                 # ⚠  No identity provider configured. All UDS callers are anonymous.\n\
                 # ⚠  Requires --insecure-identity at runtime.\n\
                 # To enable identity:\n\
                 #   [identity]\n\
                 #   provider = \"peercred\"\n",
            );
        }
    }

    out.push_str(
        "\n# --- Common customizations (uncomment as needed) ---\n\
         #\n\
         # Transport: UDS only by default. To expose a TCP listener:\n\
         #   listen_http_addr = \"127.0.0.1:3000\"\n\
         #   listen_admin_http_addr = \"127.0.0.1:3001\"\n\
         #   unsafe_expose_http = true\n\
         #   public_base_url = \"http://localhost:3000\"\n\
         #\n",
    );

    out.push_str(
        "# External backends (for HA / multi-instance):\n\
         #   redis_url = \"redis://127.0.0.1:6379\"\n\
         #   opa_url = \"http://127.0.0.1:8181\"\n\
         #\n\
         # Egress defense-in-depth (outbound HTTP proxy):\n\
         #   egress_proxy_url = \"http://squid:3128\"\n\
         #\n\
         # JWKS export (optional — for external receipt verification):\n\
         #   receipt_keys_jwks_path = \".latchgate/operators/keys/receipt.jwks\"\n\
         #\n\
         # Host I/O:\n\
         #   [host_io.database]\n\
         #   url = \"postgres://user:pass@localhost:5432/latchgate\"\n",
    );

    out
}

/// Insert a key with a preceding comment block.
fn set_commented(
    doc: &mut toml_edit::DocumentMut,
    key: &str,
    item: toml_edit::Item,
    comment: &str,
) {
    doc.insert(key, item);
    if let Some(mut key_ref) = doc.as_table_mut().key_mut(key) {
        key_ref.leaf_decor_mut().set_prefix(comment);
    }
}

/// Extract the embedded Rego policy and generate `data.json` for the preset.
///
/// `agent_principals` lists named principals (e.g. peercred-derived) that
/// should receive the wildcard grant via `inherits_wildcard`. This ensures
/// that named-identity callers are not silently denied when the Rego `*`
/// fallback is suppressed by the presence of a named ACL entry.
pub fn generate_policies(
    policies_dir: &Path,
    preset: &Preset,
    manifests_dir: &Path,
    agent_principals: &[String],
) -> Result<(), String> {
    std::fs::create_dir_all(policies_dir)
        .map_err(|e| format!("cannot create {}: {e}", policies_dir.display()))?;

    let rego_path = policies_dir.join("latchgate.rego");
    secure_file::atomic_write(&rego_path, embedded_policies::POLICY_REGO)
        .map_err(|e| format!("cannot write {}: {e}", rego_path.display()))?;

    let data_json = build_data_json(preset, manifests_dir, agent_principals)?;
    secure_file::atomic_write(&policies_dir.join("data.json"), &data_json)
        .map_err(|e| format!("cannot write data.json: {e}"))?;

    Ok(())
}

/// Build the `data.json` ACL file from preset policy rules.
///
/// Reads extracted manifests to derive action IDs, risk levels, and sinks.
/// All actions from the preset's manifests are added to the ACL — the Rego
/// policy's risk gate (step 6) holds high/critical actions for approval.
/// The preset's `wildcard_grant` is recorded for documentation but does not
/// filter ACL membership.
///
/// Each principal in `agent_principals` receives an ACL entry mirroring the
/// wildcard grant with `inherits_wildcard: true`. This is the primary fix
/// for the peercred/wildcard mismatch: named principals authenticated via
/// peercred will actually match their ACL entry instead of falling through
/// to a wildcard fallback that the Rego suppresses once a named entry exists.
pub fn build_data_json(
    preset: &Preset,
    manifests_dir: &Path,
    agent_principals: &[String],
) -> Result<String, String> {
    use latchgate_registry::manifest::ActionSpec;
    use serde_json::json;
    use std::collections::BTreeSet;

    let mut all_action_ids = BTreeSet::new();
    let mut all_sinks = BTreeSet::new();
    let mut wildcard_actions = BTreeSet::new();
    let mut wildcard_sinks = BTreeSet::new();

    let entries = std::fs::read_dir(manifests_dir)
        .map_err(|e| format!("cannot read {}: {e}", manifests_dir.display()))?;

    for entry in entries {
        let entry = entry.map_err(|e| format!("cannot read manifest entry: {e}"))?;
        let path = entry.path();
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext != "yaml" && ext != "yml" {
            continue;
        }

        let contents = std::fs::read_to_string(&path)
            .map_err(|e| format!("cannot read {}: {e}", path.display()))?;

        let spec = ActionSpec::from_yaml(&contents)
            .map_err(|e| format!("invalid manifest {}: {e}", path.display()))?;

        all_action_ids.insert(spec.action_id.clone());
        for sink in &spec.declared_side_effects {
            all_sinks.insert(sink.clone());
        }

        // Wildcard ACL: only actions the preset auto-grants (low/medium).
        // High/critical stay out of wildcard — production validation rejects
        // high-risk actions in the wildcard entry.
        if preset.wildcard_grant.allows(spec.risk_level) {
            wildcard_actions.insert(spec.action_id.clone());
            for sink in &spec.declared_side_effects {
                wildcard_sinks.insert(sink.clone());
            }
        }
    }

    // Named principals get ALL actions. High/critical pass the ACL check
    // and are caught by the Rego risk gate (step 6) for human approval.
    // The wildcard gets only the auto-grantable subset.
    let (named_actions, named_sinks) = if matches!(preset.wildcard_grant, WildcardGrant::None) {
        // Lockdown: named principals also get nothing.
        (BTreeSet::new(), BTreeSet::new())
    } else {
        (all_action_ids, all_sinks)
    };

    let policy_version = format!("{}-init", preset.name);

    let wildcard_action_list: Vec<&str> = wildcard_actions.iter().map(|s| s.as_str()).collect();
    let wildcard_sink_list: Vec<&str> = wildcard_sinks.iter().map(|s| s.as_ref()).collect();
    let named_action_list: Vec<&str> = named_actions.iter().map(|s| s.as_str()).collect();
    let named_sink_list: Vec<&str> = named_sinks.iter().map(|s| s.as_ref()).collect();

    let mut acl = serde_json::Map::new();

    // Wildcard entry — low/medium risk only. Production validation rejects
    // high/critical actions here (any anonymous caller could trigger them).
    acl.insert(
        "*".to_string(),
        json!({
            "allowed_actions": wildcard_action_list,
            "allowed_sinks": wildcard_sink_list,
        }),
    );

    // Named agent principals — ALL actions including high/critical. The Rego
    // risk gate (step 6) holds high/critical for human approval; low/medium
    // auto-allows at step 7. `inherits_wildcard` is set but the principal's
    // own allowed_actions already includes the full set.
    let grant = json!({
        "allowed_actions": named_action_list,
        "allowed_sinks": named_sink_list,
        "inherits_wildcard": true,
    });
    for principal in agent_principals {
        if principal == "*" {
            continue;
        }
        acl.insert(principal.clone(), grant.clone());
    }

    let mut data = serde_json::Map::new();
    data.insert("policy_version".to_string(), json!(policy_version));
    data.insert("acl".to_string(), json!(acl));

    // Warning for permissive presets.
    if preset.wildcard_grant.requires_dev_mode() {
        data.insert(
            "_WARNING".to_string(),
            json!("DEV-ONLY — all actions granted to wildcard. Do not deploy."),
        );
    }

    serde_json::to_string_pretty(&data).map_err(|e| format!("cannot serialize data.json: {e}"))
}
