//! Live egress allowlist synchronisation.
//!
//! Writes the effective egress domain set to a file that downstream
//! enforcement layers (Squid proxy) consume at runtime. The file is
//! updated atomically (tmp => fsync => rename) so readers never see
//! partial content.
//!
//! The effective set is:
//!   `(manifest_domains ∪ learned_domains) ∩ egress_runtime_allowlist`
//!
//! This module is called from three sites:
//! 1. Server startup — initial sync after registry + ledger are ready.
//! 2. CLI `domains add/remove/clear` — after ledger mutation.
//! 3. Approval flow — after a domain is learned through approval.

use std::collections::BTreeSet;
use std::path::Path;

use tracing::{info, warn};

use latchgate_config::Config;
use latchgate_ledger::LedgerStore;
use latchgate_registry::RegistryStore;

// atomic_write is inlined below — no CLI dependency.

// Public API

#[derive(Debug)]
pub enum SyncOutcome {
    /// No `egress_live_allowlist_path` configured — sync is a no-op.
    Disabled,
    /// File written successfully.
    Written { domain_count: usize, path: String },
}

#[derive(Debug, thiserror::Error)]
pub enum SyncError {
    #[error("failed to read learned domains from ledger: {0}")]
    Ledger(#[from] latchgate_ledger::LedgerError),

    #[error("failed to write allowlist to {path}: {source}")]
    Write {
        path: String,
        source: std::io::Error,
    },
}

/// Synchronise the live egress allowlist file from registry + ledger.
///
/// Returns `Ok(Disabled)` when `egress_live_allowlist_path` is not set.
/// Returns `Ok(Written { .. })` on success. IO or ledger errors propagate.
pub fn sync(
    config: &Config,
    registry: &RegistryStore,
    ledger: &LedgerStore,
) -> Result<SyncOutcome, SyncError> {
    let path = match &config.egress.egress_live_allowlist_path {
        Some(p) => p.clone(),
        None => return Ok(SyncOutcome::Disabled),
    };

    // ── Collect manifest domains ──────────────────────────────────────
    let mut domains = BTreeSet::new();
    for spec in registry.list_actions() {
        if let Ok(profile) = spec.egress_profile() {
            for d in profile.concrete_allowed_domains() {
                domains.insert(d.to_string());
            }
        }
    }

    // ── Merge learned domains ─────────────────────────────────────────
    let learned = ledger.list_learned_domains(None)?;
    for entry in &learned {
        domains.insert(entry.domain.clone());
    }

    // ── Apply runtime narrowing ───────────────────────────────────────
    let mut domains_vec: Vec<String> = domains.into_iter().collect();
    config.narrow_egress_domains(&mut domains_vec);

    // ── Write Squid-format allowlist ──────────────────────────────────
    let dest = Path::new(&path);
    if let Some(parent) = dest.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent).map_err(|e| SyncError::Write {
                path: path.clone(),
                source: e,
            })?;
        }
    }

    let content = render_squid_allowlist(&domains_vec);
    atomic_write(dest, &content).map_err(|e| SyncError::Write {
        path: path.clone(),
        source: e,
    })?;

    let domain_count = domains_vec.len();

    info!(
        path = %path,
        domain_count = domain_count,
        "live egress allowlist written"
    );

    // ── Reload command ────────────────────────────────────────────────
    if let Some(cmd) = &config.egress.egress_reload_command {
        run_reload_command(cmd);
    }

    Ok(SyncOutcome::Written { domain_count, path })
}

/// Synchronise using only config + ledger (no running registry).
pub fn sync_from_disk(config: &Config, ledger: &LedgerStore) -> Result<SyncOutcome, SyncError> {
    let path = match &config.egress.egress_live_allowlist_path {
        Some(p) => p.clone(),
        None => return Ok(SyncOutcome::Disabled),
    };

    // Load manifests from disk — same path the server uses at startup.
    let manifests_dir = Path::new(&config.manifests_dir);
    let registry = match RegistryStore::load_from_dir(manifests_dir) {
        Ok(r) => r,
        Err(e) => {
            warn!(
                manifests_dir = %config.manifests_dir,
                error = %e,
                path = %path,
                "cannot load manifests for live egress sync — skipping file update"
            );
            return Ok(SyncOutcome::Disabled);
        }
    };

    sync(config, &registry, ledger)
}

// Internal helpers

/// Render domain list in Squid `dstdomain` format.
fn render_squid_allowlist(domains: &[String]) -> String {
    let mut out = String::with_capacity(domains.len() * 30);
    out.push_str("# Live egress allowlist — generated by LatchGate.\n");
    out.push_str("# manifest_domains ∪ learned_domains ∩ runtime_allowlist\n");
    out.push_str("# DO NOT EDIT — regenerated on domain changes.\n");

    // Squid dstdomain format: leading dot matches domain + all subdomains.
    // Manifest wildcards (*.example.com) are normalised to .example.com.
    for domain in domains {
        if let Some(stripped) = domain.strip_prefix("*.") {
            out.push('.');
            out.push_str(stripped);
        } else {
            out.push('.');
            out.push_str(domain);
        }
        out.push('\n');
    }

    out
}

/// Run the operator's reload command. Log but do not fail on error.
fn run_reload_command(cmd: &str) {
    info!(command = %cmd, "running egress reload command");

    match std::process::Command::new("sh").args(["-c", cmd]).output() {
        Ok(output) => {
            if output.status.success() {
                info!(command = %cmd, "egress reload command succeeded");
            } else {
                let stderr = String::from_utf8_lossy(&output.stderr);
                warn!(
                    command = %cmd,
                    exit_code = ?output.status.code(),
                    stderr = %stderr,
                    "egress reload command returned non-zero — Squid may need manual reload"
                );
            }
        }
        Err(e) => {
            warn!(
                command = %cmd,
                error = %e,
                "failed to execute egress reload command"
            );
        }
    }
}

// Tests

fn atomic_write(path: &Path, content: &str) -> std::io::Result<()> {
    latchgate_core::atomic_write_str(path, content)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_squid_allowlist_format() {
        let domains = vec!["api.github.com".to_string(), "api.stripe.com".to_string()];
        let out = render_squid_allowlist(&domains);

        assert!(out.contains(".api.github.com\n"));
        assert!(out.contains(".api.stripe.com\n"));
        assert!(out.contains("DO NOT EDIT"));
    }

    #[test]
    fn render_squid_normalises_wildcards() {
        let domains = vec!["*.wikipedia.org".to_string()];
        let out = render_squid_allowlist(&domains);

        assert!(out.contains(".wikipedia.org\n"));
        assert!(!out.contains("*.wikipedia.org"));
    }

    #[test]
    fn render_squid_empty_domains() {
        let out = render_squid_allowlist(&[]);
        // Should still have the header, just no domain lines.
        assert!(out.contains("DO NOT EDIT"));
        let non_comment_lines: Vec<&str> = out
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert!(non_comment_lines.is_empty());
    }

    #[test]
    fn sync_disabled_when_no_path_configured() {
        let config = Config::default();
        assert!(config.egress.egress_live_allowlist_path.is_none());

        let registry = RegistryStore::empty();
        let ledger = LedgerStore::open_in_memory(None).unwrap();

        let result = sync(&config, &registry, &ledger).unwrap();
        assert!(matches!(result, SyncOutcome::Disabled));
    }

    #[test]
    fn sync_writes_file_with_manifest_and_learned_domains() {
        let tmp = tempfile::tempdir().unwrap();
        let allowlist_path = tmp.path().join("allowlist.txt");

        let config = Config {
            egress: latchgate_config::EgressConfig {
                egress_live_allowlist_path: Some(allowlist_path.display().to_string()),
                ..Default::default()
            },
            ..Config::default()
        };

        let registry = RegistryStore::empty();
        let ledger = LedgerStore::open_in_memory(None).unwrap();
        ledger
            .add_learned_domain(
                "web_read",
                "learned.example.com",
                "alice",
                latchgate_ledger::EntrySource::Cli,
                None,
                false,
            )
            .unwrap();

        let result = sync(&config, &registry, &ledger).unwrap();
        match result {
            SyncOutcome::Written { domain_count, .. } => {
                assert_eq!(domain_count, 1);
            }
            SyncOutcome::Disabled => panic!("expected Written"),
        }

        let content = std::fs::read_to_string(&allowlist_path).unwrap();
        assert!(content.contains(".learned.example.com"));
    }

    #[test]
    fn sync_applies_runtime_narrowing() {
        let tmp = tempfile::tempdir().unwrap();
        let allowlist_path = tmp.path().join("allowlist.txt");

        let config = Config {
            egress: latchgate_config::EgressConfig {
                egress_live_allowlist_path: Some(allowlist_path.display().to_string()),
                egress_runtime_allowlist: Some(vec!["kept.com".to_string()]),
                ..Default::default()
            },
            ..Config::default()
        };

        let registry = RegistryStore::empty();
        let ledger = LedgerStore::open_in_memory(None).unwrap();
        ledger
            .add_learned_domain(
                "a",
                "kept.com",
                "op",
                latchgate_ledger::EntrySource::Cli,
                None,
                false,
            )
            .unwrap();
        ledger
            .add_learned_domain(
                "b",
                "dropped.com",
                "op",
                latchgate_ledger::EntrySource::Cli,
                None,
                false,
            )
            .unwrap();

        sync(&config, &registry, &ledger).unwrap();

        let content = std::fs::read_to_string(&allowlist_path).unwrap();
        assert!(content.contains(".kept.com"));
        assert!(!content.contains("dropped.com"));
    }
}
