//! Compile-time embedded WASM provider modules.
//!
//! The actual `PROVIDERS` slice is generated by `build.rs`:
//! - If `target/providers/*.wasm` exist at build time: bytes are embedded.
//! - If missing (dev without `make providers`): slice is empty and the
//!   server relies on filesystem-loaded providers from `wasm_providers_dir`.
//!
//! Release builds must run `make providers` before `cargo build` to produce
//! a self-contained binary.

include!(concat!(env!("OUT_DIR"), "/embedded_providers.gen.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn providers_slice_is_valid() {
        let mut seen = std::collections::HashSet::new();
        for (name, bytes) in PROVIDERS {
            assert!(!name.is_empty(), "provider name must not be empty");
            assert!(seen.insert(name), "duplicate provider name: {name}");

            if !bytes.is_empty() {
                assert!(
                    bytes.len() >= 4 && bytes[..4] == [0x00, 0x61, 0x73, 0x6d],
                    "embedded provider '{name}' does not start with WASM magic bytes"
                );
            }
        }
    }
}
