//! Regression guard for the post-dispatch evidence-failure invariant.
//!
//! The execution pipeline debits budget before dispatching the provider
//! and finalises (receipt + audit) after. If the finalise step fails
//! *after* a successful dispatch, the side effect has already happened
//! — the HTTP POST was sent, the row was written, the email left the
//! relay — and refunding the budget would let the client replay the
//! same one-shot authorisation and cause the effect twice.
//!
//! The kernel's contract on that branch is:
//!   1. Do NOT rollback the budget (side effect is already out).
//!   2. Return `EvidencePersistenceFailed` (HTTP 500).
//!   3. Leave the pre-dispatch `ExecutionIntent` as a forensic marker
//!      so operators can correlate intents against receipts and triage
//!      the partial state manually.
//!
//! This module asserts all three properties end-to-end, through the
//! real HTTP surface, against real Redis/OPA. The evidence-failure
//! signal is generated by the `test-hooks` fault-injection API on the
//! ledger — deterministic, one-shot, cfg-gated so release builds have
//! no runtime surface for arming a fault.

use axum::http::StatusCode;
use latchgate_state::BudgetManager;

use crate::harness::{
    action_url, post_json, post_json_operator, post_with_auth, test_redis_url,
    test_router_with_probe, Agent, PROBE_ACTION_ID, PROBE_APPROVAL_ACTION_ID,
};

/// Budget allowance for the probe call. Must be ≥ 2 so that, after the
/// first call consumes one unit, the post-call snapshot is strictly
/// less than the pre-call snapshot (proving no refund) AND the session
/// could still make a second call (proving the debit was persistent,
/// not lost to some other path).
const PROBE_BUDGET_CALLS: u64 = 5;

/// Issue a lease with an explicit call budget.
async fn issue_probe_lease(app: &axum::Router, agent: &Agent) -> (String, String) {
    let body = serde_json::json!({
        "dpop_jwk": agent.jwk_json(),
        "scopes": ["tools:call"],
        "budgets": {
            "max_calls": PROBE_BUDGET_CALLS,
        },
    });
    let (status, json) = post_json(app, "/v1/leases", &body).await;
    assert_eq!(
        status,
        StatusCode::OK,
        "probe lease issuance failed: {json}"
    );
    let jwt = json["lease_jwt"].as_str().unwrap().to_string();
    let sid = json["session_id"].as_str().unwrap().to_string();
    (jwt, sid)
}

/// SECURITY: evidence-finalisation failure after a successful WASM
/// dispatch must NOT refund the session budget. Refunding would allow
/// the caller to retry and re-trigger the already-happened side effect.
#[tokio::test]
async fn evidence_persistence_failure_does_not_refund_budget() {
    let (app, ledger, state) = test_router_with_probe();
    let agent = Agent::new();

    let (lease_jwt, session_id) = issue_probe_lease(&app, &agent).await;

    // Snapshot budget before the call. Uses the same BudgetManager the
    // kernel uses — observes exactly what the kernel observes.
    let budget_probe =
        BudgetManager::new(&test_redis_url()).expect("budget manager connects to test redis");
    let before = budget_probe
        .get_snapshot(&session_id)
        .await
        .expect("snapshot before call");
    assert_eq!(
        before.calls_remaining, PROBE_BUDGET_CALLS as i64,
        "lease issuance must set the initial call allowance: {before:?}"
    );

    // Arm the one-shot finalize failure. The next finalize_evidence()
    // call (which runs after WASM dispatch succeeds) returns Err;
    // subsequent calls run normally.
    ledger.arm_finalize_failure();

    let htu = action_url(PROBE_ACTION_ID);
    let proof = agent.dpop_proof("POST", &htu, &lease_jwt);
    let (status, body) = post_with_auth(
        &app,
        &format!("/v1/actions/{PROBE_ACTION_ID}/execute"),
        &lease_jwt,
        &proof,
        &serde_json::json!({}),
    )
    .await;

    // -- Property 1: client receives 500 + evidence_persistence_failed.
    assert_eq!(
        status,
        StatusCode::INTERNAL_SERVER_ERROR,
        "armed evidence failure must surface as 500, got body: {body}"
    );
    assert_eq!(
        body["error"].as_str(),
        Some("evidence_persistence_failed"),
        "response body must carry the structured evidence-failure code: {body}"
    );

    // -- Property 2: budget was debited and NOT refunded.
    let after = budget_probe
        .get_snapshot(&session_id)
        .await
        .expect("snapshot after call");
    assert_eq!(
        after.calls_remaining,
        before.calls_remaining - 1,
        "budget must remain debited after evidence failure — refunding would \
         allow replay of an already-executed side effect. before={before:?}, after={after:?}"
    );

    // -- Property 3: a pre-dispatch ExecutionIntent survives as a
    //    forensic marker for the failed execution. The kernel writes
    //    the intent to ledger BEFORE dispatching. Finalise failing
    //    means the intent is now unmatched by a receipt — operators
    //    query `get_unresolved_intents()` to triage which side effects
    //    may have occurred.
    //
    //    An audit event is NOT written on this branch: audit + receipt
    //    are finalised together in a single transaction, and that
    //    transaction is what failed. The intent without a matching
    //    receipt is the sole forensic artifact.
    let unresolved = ledger
        .get_unresolved_intents()
        .expect("list unresolved intents");
    let matching = unresolved
        .iter()
        .filter(|intent| *intent.action_id == *PROBE_ACTION_ID)
        .count();
    assert!(
        matching >= 1,
        "an ExecutionIntent for {PROBE_ACTION_ID} must survive as a forensic marker \
         (unresolved intents: {unresolved:?})"
    );

    // -- Sanity: the fault is one-shot. A second call with the same
    //    lease succeeds, proving the arm cleared itself and that the
    //    remaining budget is usable.
    let proof2 = agent.dpop_proof("POST", &htu, &lease_jwt);
    let (status2, body2) = post_with_auth(
        &app,
        &format!("/v1/actions/{PROBE_ACTION_ID}/execute"),
        &lease_jwt,
        &proof2,
        &serde_json::json!({}),
    )
    .await;
    assert_eq!(
        status2,
        StatusCode::OK,
        "follow-up call must succeed (fault is one-shot), got body: {body2}"
    );

    drop(state);
}

/// SECURITY: the approval path has its own budget debit (in
/// `prepare_approved_execution`, not `step_debit_budget`) but shares
/// the `execute_authorized_plan` tail with auto-allow. The same
/// evidence-failure invariant must hold: a finalise failure after a
/// successful dispatch must NOT refund the debit, regardless of which
/// path produced the `AuthorizedExecution`.
///
/// This test exercises that symmetry by driving a high-risk action
/// (`evidence_probe_approval`) through:
///     POST /v1/actions/.../execute   => 202, pending created, no debit
///     arm finalize_evidence fault
///     POST /v1/approvals/{id}/approve => debit + dispatch + armed
///                                        finalise failure => 500
/// then asserts the same three properties the auto-allow test asserts.
#[tokio::test]
async fn evidence_persistence_failure_on_approval_path_does_not_refund_budget() {
    let (app, ledger, state) = test_router_with_probe();
    let agent = Agent::new();

    let (lease_jwt, session_id) = issue_probe_lease(&app, &agent).await;

    let budget_probe =
        BudgetManager::new(&test_redis_url()).expect("budget manager connects to test redis");
    let before = budget_probe
        .get_snapshot(&session_id)
        .await
        .expect("snapshot before pending");
    assert_eq!(
        before.calls_remaining, PROBE_BUDGET_CALLS as i64,
        "lease issuance must set the initial call allowance: {before:?}"
    );

    // -- Step 1: pending creation. High-risk action + OPA policy =>
    //    pending_approval decision. No budget debit on this path; the
    //    debit happens only after an operator claims + approves.
    let htu_exec = action_url(PROBE_APPROVAL_ACTION_ID);
    let proof_exec = agent.dpop_proof("POST", &htu_exec, &lease_jwt);
    let (status_exec, body_exec) = post_with_auth(
        &app,
        &format!("/v1/actions/{PROBE_APPROVAL_ACTION_ID}/execute"),
        &lease_jwt,
        &proof_exec,
        &serde_json::json!({}),
    )
    .await;
    assert_eq!(
        status_exec,
        StatusCode::ACCEPTED,
        "high-risk action must return 202 pending, got body: {body_exec}"
    );
    let approval_id = body_exec["approval_id"]
        .as_str()
        .expect("202 response must carry approval_id")
        .to_string();

    // Sanity: pending creation does NOT debit the budget.
    let after_pending = budget_probe
        .get_snapshot(&session_id)
        .await
        .expect("snapshot after pending");
    assert_eq!(
        after_pending.calls_remaining, before.calls_remaining,
        "pending creation must not debit budget — the debit is performed \
         in prepare_approved_execution, gated on operator approval \
         (before={before:?}, after_pending={after_pending:?})"
    );

    // -- Step 2: arm the one-shot finalise failure BEFORE approval.
    //    The approval handler calls prepare_approved_execution (debit)
    //    then execute_authorized_plan (dispatch, then finalise). The
    //    armed fault fires during finalise, after dispatch has
    //    already produced the side effect.
    ledger.arm_finalize_failure();

    // -- Step 3: approve. Must surface the finalise failure as 500,
    //    matching the auto-allow path's contract.
    let (status_approve, body_approve) = post_json_operator(
        &app,
        &format!("/v1/approvals/{approval_id}/approve"),
        &serde_json::json!({}),
    )
    .await;
    assert_eq!(
        status_approve,
        StatusCode::INTERNAL_SERVER_ERROR,
        "armed evidence failure on approval path must surface as 500, \
         got body: {body_approve}"
    );
    assert_eq!(
        body_approve["error"].as_str(),
        Some("evidence_persistence_failed"),
        "approval response must carry the same structured error code as \
         the auto-allow path: {body_approve}"
    );

    // -- Property 1: approval path debited the budget exactly once,
    //    and the evidence-failure branch did NOT refund it. The debit
    //    is issued by prepare_approved_execution (step 7), observed
    //    here as a decrease from the pre-approval snapshot.
    let after_approval = budget_probe
        .get_snapshot(&session_id)
        .await
        .expect("snapshot after approval");
    assert_eq!(
        after_approval.calls_remaining,
        after_pending.calls_remaining - 1,
        "approval path must debit budget and retain the debit on evidence \
         failure (after_pending={after_pending:?}, after_approval={after_approval:?})"
    );

    // -- Property 2: the pre-dispatch ExecutionIntent survives as a
    //    forensic marker for the approved-but-unfinalised execution.
    //    Same invariant as the auto-allow path; different action_id.
    let unresolved = ledger
        .get_unresolved_intents()
        .expect("list unresolved intents");
    let matching = unresolved
        .iter()
        .filter(|intent| *intent.action_id == *PROBE_APPROVAL_ACTION_ID)
        .count();
    assert!(
        matching >= 1,
        "an ExecutionIntent for {PROBE_APPROVAL_ACTION_ID} must survive \
         as a forensic marker (unresolved intents: {unresolved:?})"
    );

    drop(state);
}
