/**
 * Cryptographic primitives for DPoP (RFC 9449) using P-256 / ES256.
 *
 * Uses the Web Crypto API (`globalThis.crypto.subtle`) available natively
 * in Node.js 18+. No external crypto dependencies required.
 *
 * Security notes
 * --------------
 * - Private keys are held as non-extractable CryptoKey objects — the runtime
 *   prevents them from ever being serialised or leaked.
 * - Each DPoP proof uses a fresh `jti` (UUID) and current Unix time as `iat`.
 * - `ath` (access token hash) binds the proof to the specific lease JWT,
 *   preventing proof reuse across different tokens.
 * - Web Crypto ECDSA produces IEEE P1363 signatures (raw r||s), which is
 *   exactly the 64-byte format required by JWT ES256 — no conversion needed.
 */

// ---------------------------------------------------------------------------
// Base64url helpers
// ---------------------------------------------------------------------------

function b64url(bytes: Uint8Array): string {
  let str = "";
  // Process in 32 KB chunks — well below V8's ~65 536 apply-argument limit.
  for (let i = 0; i < bytes.length; i += 0x8000) {
    str += String.fromCharCode.apply(
      null,
      bytes.subarray(i, i + 0x8000) as unknown as number[],
    );
  }
  return btoa(str)
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replaceAll("=", "");
}

function b64urlEncode(str: string): string {
  return b64url(new TextEncoder().encode(str));
}

// ---------------------------------------------------------------------------
// DPoPKeyPair
// ---------------------------------------------------------------------------

export interface DPoPJwk {
  kty: "EC";
  crv: "P-256";
  x: string;
  y: string;
}

export class DPoPKeyPair {
  /** Public key in JWK format. Send to POST /v1/leases as `dpop_jwk`. */
  readonly jwk: DPoPJwk;
  private readonly privateKey: CryptoKey;

  private constructor(jwk: DPoPJwk, privateKey: CryptoKey) {
    this.jwk = jwk;
    this.privateKey = privateKey;
  }

  /** Generate a fresh P-256 key pair. */
  static async generate(): Promise<DPoPKeyPair> {
    const keyPair = await crypto.subtle.generateKey(
      { name: "ECDSA", namedCurve: "P-256" },
      // Private key is non-extractable — cannot be serialised or leaked.
      false,
      ["sign"],
    );

    // Export only the public key to build the JWK for lease issuance.
    const pubJwk = await crypto.subtle.exportKey("jwk", keyPair.publicKey);

    const jwk: DPoPJwk = {
      kty: "EC",
      crv: "P-256",
      // Web Crypto exports x/y as base64url without padding — exactly the
      // format required by RFC 7638 and the LatchGate lease endpoint.
      x: pubJwk.x as string,
      y: pubJwk.y as string,
    };

    return new DPoPKeyPair(jwk, keyPair.privateKey);
  }

  /**
   * Load an operator P-256 key pair from a PKCS#8 PEM string.
   *
   * Use this to load operator keys generated by `latchgate init`
   * (stored in `.latchgate/*.pem`).
   */
  static async fromPem(pem: string): Promise<DPoPKeyPair> {
    // Strip PEM envelope and decode base64 to raw PKCS#8 DER.
    const b64 = pem
      .replace(/-----BEGIN PRIVATE KEY-----/g, "")
      .replace(/-----END PRIVATE KEY-----/g, "")
      .replace(/\s/g, "");
    const der = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

    // Import as extractable first so we can derive the public coordinates.
    const extractable = await crypto.subtle.importKey(
      "pkcs8",
      der,
      { name: "ECDSA", namedCurve: "P-256" },
      true,
      ["sign"],
    );
    const fullJwk = await crypto.subtle.exportKey("jwk", extractable);

    const jwk: DPoPJwk = {
      kty: "EC",
      crv: "P-256",
      x: fullJwk.x as string,
      y: fullJwk.y as string,
    };

    // Re-import as non-extractable for actual signing — matches generate().
    const signingKey = await crypto.subtle.importKey(
      "pkcs8",
      der,
      { name: "ECDSA", namedCurve: "P-256" },
      false,
      ["sign"],
    );

    return new DPoPKeyPair(jwk, signingKey);
  }

  /**
   * Load an operator P-256 key pair from a PEM file path.
   *
   * Convenience wrapper around {@link fromPem}. Requires Node.js `fs`.
   */
  static async fromPemFile(path: string): Promise<DPoPKeyPair> {
    const { readFileSync } = await import("node:fs");
    const pem = readFileSync(path, "utf-8");
    return DPoPKeyPair.fromPem(pem);
  }

  /**
   * Build and sign a DPoP proof JWT.
   *
   * @param htm - HTTP method in uppercase (e.g. `"POST"`).
   * @param htu - Full request URI without fragment or query string.
   * @param ath - Access token hash — `computeAth(leaseJwt)`.
   * @returns Compact serialisation of the signed DPoP proof JWT.
   */
  async signProof(htm: string, htu: string, ath: string): Promise<string> {
    const header = { typ: "dpop+jwt", alg: "ES256", jwk: this.jwk };
    const payload = {
      jti: crypto.randomUUID(),
      htm: htm.toUpperCase(),
      htu: normalizeHtu(htu),
      iat: Math.floor(Date.now() / 1000),
      ath,
    };

    const headerB64 = b64urlEncode(JSON.stringify(header));
    const payloadB64 = b64urlEncode(JSON.stringify(payload));
    const signingInput = `${headerB64}.${payloadB64}`;

    // ECDSA with Web Crypto produces IEEE P1363 (raw r||s) — the 64-byte
    // format required by JWT ES256. No DER conversion needed.
    const sigBytes = await crypto.subtle.sign(
      { name: "ECDSA", hash: "SHA-256" },
      this.privateKey,
      new TextEncoder().encode(signingInput),
    );

    return `${signingInput}.${b64url(new Uint8Array(sigBytes))}`;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Compute the `ath` claim: base64url(SHA-256(leaseJwt)).
 *
 * Binds the DPoP proof to a specific lease token so that a proof intercepted
 * from one request cannot be replayed with a different token.
 */
export async function computeAth(leaseJwt: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(leaseJwt),
  );
  return b64url(new Uint8Array(digest));
}

/**
 * Normalize a URI for DPoP `htu` comparison (RFC 9449 §4.2.2).
 *
 * Must match the server's `normalize_htu` in
 * `crates/latchgate-auth/src/dpop/mod.rs` exactly:
 *
 * 1. Strip fragment and query string.
 * 2. Lowercase scheme and authority (path case is preserved).
 * 3. Strip default ports (`:80` for HTTP, `:443` for HTTPS).
 * 4. Bare authority without a path gets `/`.
 */
export function normalizeHtu(uri: string): string {
  // Remove fragment
  uri = uri.split("#")[0] ?? uri;
  // Remove query string
  uri = uri.split("?")[0] ?? uri;

  // Split scheme from the rest
  const sepIdx = uri.indexOf("://");
  if (sepIdx === -1) return uri; // no scheme — return as-is

  const scheme = uri.slice(0, sepIdx).toLowerCase();
  const afterScheme = uri.slice(sepIdx + 3);

  // Split authority from path on the first slash
  const slashIdx = afterScheme.indexOf("/");
  let authority: string;
  let path: string;
  if (slashIdx === -1) {
    authority = afterScheme.toLowerCase();
    path = "/";
  } else {
    authority = afterScheme.slice(0, slashIdx).toLowerCase();
    path = afterScheme.slice(slashIdx); // includes leading '/'
  }

  // Strip default ports — lastIndexOf handles IPv6 bracket-addresses correctly
  authority = stripDefaultPort(authority, scheme);

  return `${scheme}://${authority}${path}`;
}

/**
 * Strip the default port from an authority string (HTTP → 80, HTTPS → 443).
 *
 * Uses `lastIndexOf(":")` so IPv6 bracket-addresses (`[::1]:8080`) are
 * handled correctly — the port separator is always the last colon.
 */
function stripDefaultPort(authority: string, scheme: string): string {
  const idx = authority.lastIndexOf(":");
  if (idx === -1) return authority;
  const host = authority.slice(0, idx);
  const port = authority.slice(idx + 1);
  if (
    (scheme === "http" && port === "80") ||
    (scheme === "https" && port === "443")
  ) {
    return host;
  }
  return authority;
}
