"""Cryptographic primitives for DPoP (RFC 9449) using P-256 / ES256.

Security notes
--------------
- Private keys are held in memory only. They are never written to disk
  or included in any log, trace, or exception message.
- Each DPoP proof uses a fresh ``jti`` (UUID4) and the current Unix time
  as ``iat``.  The server enforces a narrow clock-skew window and rejects
  replayed ``jti`` values.
- ``ath`` (access token hash) binds the proof to the specific lease JWT,
  preventing proof reuse across different tokens.
"""

from __future__ import annotations

import base64
import hashlib
import json
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature


def _b64url(data: bytes) -> str:
    """Base64url-encode *data* without padding."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64url_int(n: int, byte_length: int = 32) -> str:
    """Encode an integer as a fixed-width big-endian base64url string."""
    return _b64url(n.to_bytes(byte_length, "big"))


@dataclass(frozen=True)
class DPoPKeyPair:
    """An ES256 key pair for DPoP proof generation.

    ``jwk`` is the *public* key in JWK format, suitable for sending to
    ``POST /v1/leases`` as ``dpop_jwk``.

    The private key is held in ``_private`` and never exposed as a plain
    attribute to reduce the risk of accidental serialisation.
    """

    jwk: dict[str, str]
    _private: ec.EllipticCurvePrivateKey

    @classmethod
    def generate(cls) -> DPoPKeyPair:
        """Generate a fresh P-256 key pair."""
        private = ec.generate_private_key(ec.SECP256R1())
        return cls._from_private_key(private)

    @classmethod
    def from_pem(cls, pem_data: str | bytes) -> DPoPKeyPair:
        """Load a P-256 key pair from a PKCS#8 PEM string or bytes.

        Use this to load operator keys generated by ``latchgate init``
        (stored at ``.latchgate/<name>.pem``).

        Parameters
        ----------
        pem_data:
            PEM-encoded PKCS#8 private key (contents of the ``.pem`` file).

        Raises
        ------
        ValueError
            If the PEM does not contain a P-256 key.
        """
        from cryptography.hazmat.primitives.serialization import load_pem_private_key

        if isinstance(pem_data, str):
            pem_data = pem_data.encode("utf-8")

        private = load_pem_private_key(pem_data, password=None)
        if not isinstance(private, ec.EllipticCurvePrivateKey):
            raise ValueError("PEM does not contain an EC private key")
        if not isinstance(private.curve, ec.SECP256R1):
            raise ValueError(
                f"expected P-256 (secp256r1) key, got {private.curve.name}"
            )
        return cls._from_private_key(private)

    @classmethod
    def from_pem_file(cls, path: str | Path) -> DPoPKeyPair:
        """Load a P-256 key pair from a PEM file on disk.

        Convenience wrapper around :meth:`from_pem`.

        Parameters
        ----------
        path:
            Path to a PKCS#8 PEM file (e.g. ``.latchgate/default.pem``).
        """
        pem_data = Path(path).read_bytes()
        return cls.from_pem(pem_data)

    @classmethod
    def _from_private_key(cls, private: ec.EllipticCurvePrivateKey) -> DPoPKeyPair:
        """Build a DPoPKeyPair from an existing private key."""
        pub = private.public_key()
        pub_numbers = pub.public_numbers()
        jwk = {
            "kty": "EC",
            "crv": "P-256",
            "x": _b64url_int(pub_numbers.x),
            "y": _b64url_int(pub_numbers.y),
        }
        return cls(jwk=jwk, _private=private)

    def sign_proof(self, htm: str, htu: str, ath: str) -> str:
        """Build and sign a DPoP proof JWT.

        Parameters
        ----------
        htm:
            HTTP method in uppercase (e.g. ``"POST"``).
        htu:
            Full request URI without fragment or query string
            (e.g. ``"http://localhost:8080/v1/actions/http_fetch/execute"``).
        ath:
            Access token hash — ``compute_ath(lease_jwt)``.

        Returns
        -------
        str
            Compact serialisation of the signed DPoP proof JWT.
        """
        header = {
            "typ": "dpop+jwt",
            "alg": "ES256",
            "jwk": self.jwk,
        }
        payload = {
            "jti": str(uuid.uuid4()),
            "htm": htm.upper(),
            "htu": _normalize_htu(htu),
            "iat": int(time.time()),
            "ath": ath,
        }

        header_b64 = _b64url(json.dumps(header, separators=(",", ":")).encode())
        payload_b64 = _b64url(json.dumps(payload, separators=(",", ":")).encode())
        signing_input = f"{header_b64}.{payload_b64}".encode()

        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.asymmetric import ec as _ec

        der_sig = self._private.sign(signing_input, _ec.ECDSA(hashes.SHA256()))

        # JWT ES256 requires raw (r || s) 64-byte encoding, not DER.
        r, s = decode_dss_signature(der_sig)
        raw_sig = r.to_bytes(32, "big") + s.to_bytes(32, "big")

        return f"{header_b64}.{payload_b64}.{_b64url(raw_sig)}"


def compute_ath(token: str) -> str:
    """Compute the ``ath`` claim: SHA-256 of the token, base64url-encoded.

    This binds the DPoP proof to a specific token so that a proof
    intercepted from one request cannot be replayed with a different token.

    Works for both lease JWTs (agent auth) and operator API keys
    (operator auth).
    """
    digest = hashlib.sha256(token.encode("ascii")).digest()
    return _b64url(digest)


def _normalize_htu(uri: str) -> str:
    """Normalize a URI for DPoP ``htu`` comparison (RFC 9449 §4.2.2).

    Must match the server's ``normalize_htu`` in
    ``crates/latchgate-auth/src/dpop/mod.rs`` exactly:

    1. Strip fragment and query string.
    2. Lowercase scheme and authority (path case is preserved).
    3. Strip default ports (``:80`` for HTTP, ``:443`` for HTTPS).
    4. Bare authority without a path gets ``/``.
    """
    # Remove fragment
    uri = uri.split("#", 1)[0]
    # Remove query string
    uri = uri.split("?", 1)[0]

    # Split scheme from the rest
    sep_idx = uri.find("://")
    if sep_idx == -1:
        # No scheme — return as-is; the server would reject this URI.
        return uri

    scheme = uri[:sep_idx].lower()
    after_scheme = uri[sep_idx + 3 :]

    # Split authority from path on the first slash
    slash_idx = after_scheme.find("/")
    if slash_idx == -1:
        authority = after_scheme.lower()
        path = "/"
    else:
        authority = after_scheme[:slash_idx].lower()
        path = after_scheme[slash_idx:]  # includes leading '/'

    # Strip default ports — rfind handles IPv6 bracket-addresses correctly
    authority = _strip_default_port(authority, scheme)

    return f"{scheme}://{authority}{path}"


def _strip_default_port(authority: str, scheme: str) -> str:
    """Strip the default port from *authority* (HTTP → 80, HTTPS → 443).

    Uses ``rfind(":")`` so IPv6 bracket-addresses (``[::1]:8080``) are
    handled correctly — the port separator is always the last colon.
    """
    idx = authority.rfind(":")
    if idx == -1:
        return authority
    host, port = authority[:idx], authority[idx + 1 :]
    if (scheme == "http" and port == "80") or (scheme == "https" and port == "443"):
        return host
    return authority
